### ISSUE TITLE
[Question]是否应该对源站投稿频率持续过高做出相应的妥协处理

### ISSUE THREAD

**Issue by VonXXGhost** [ElnathMojo/sakugabot#15]
仅从ID上判断已经落后600+条了，以目前的投稿速率和微博API限制的情况上看，差距只会越拉越大无法追上，对时效性方面的影响很大。所以是否应该做出一些处理从而使库存快速消耗，如：

1.  手动标记跳过部分已投稿过的老作品（新投稿中占比很大的一部分是旧稿微调后重投的）

2. 设立新号（但各种层面上的成本都很大）

**Comment by ElnathMojo** [comment]
尝试让它能每天发送超过100条中，之后再考虑可能的人工介入。
