### ISSUE TITLE
关于最近微博收紧登录安全的问题

### ISSUE THREAD

**Issue by VonXXGhost** [ElnathMojo/sakugabot#16]
从前段时间开始微博收紧了登录政策，现在网页版登录需要扫码/短信/私信验证三选一，客户端登录也需要手机验证，导致我现在没法查收评论反馈和私信情况……能否有较好的解决方案。

**Comment by ElnathMojo** [comment]
最好是登陆一个手机客户端，之后扫码。
你现在要登陆的
